export const SERVICES = {
    GET_DEFAULT_SERVICES_ICE: 'SERVICES/GET_DEFAULT_SERVICES_ICE',
    SET_DEFAULT_SERVICE: 'SERVICES/SET_DEFAULT_SERVICE',
    DELETE_SERVICE: 'SERVICES/DELETE_SERVICE',
    GET_SERVICE_BY_NAME: 'SERVICES/GET_SERVICE_BY_NAME',

    GET_DEFAULT_SERVICES_SUSPENSION: 'SERVICES/GET_DEFAULT_SERVICES_SUSPENSION',
    SET_DEFAULT_SERVICE_SUSPENSION: 'SERVICES/SET_DEFAULT_SERVICE_SUSPENSION',
    DELETE_SERVICE_SUSPENSION: 'SERVICES/DELETE_SERVICE_SUSPENSION',

    GET_DEFAULT_SERVICES_ELECTRICIAN: 'SERVICES/GET_DEFAULT_SERVICES_ELECTRICIAN',
    SET_DEFAULT_SERVICE_ELECTRICIAN: 'SERVICES/SET_DEFAULT_SERVICE_ELECTRICIAN',
    DELETE_SERVICE_ELECTRICIAN: 'SERVICES/DELETE_SERVICE_ELECTRICIAN',
}

export const REPAIRS = {
    GET_DEFAULT_REPAIRS: 'REPAIRS/GET_DEFAULT_REPAIRS',
    DELETE_REPAIR: 'REPAIRS/DELETE_REPAIR',
    EDIT_REPAIR: 'REPAIRS/EDIT_REPAIR',
    SET_DEFAULT_REPAIR: 'REPAIRS/SET_DEFAULT_REPAIR',
}

export const EMPLOYEES = {
    GET_DEFAULT_EMPLOYEES: 'EMPLOYEES/GET_DEFAULT_EMPLOYEES',
    SET_DEFAULT_EMPLOYEE: 'EMPLOYEES/SET_DEFAULT_EMPLOYEE',
    DELETE_EMPLOYEE: 'EMPLOYEES/DELETE_EMPLOYEE',
    EDIT_EMPLOYEE: 'EMPLOYEE/EDIT_EMPLOYEE'
}

export const USERS = {
    GET_DEFAULT_USERS: 'USERS/GET_DEFAULT_USERS',
    DELETE_USER: 'USERS/DELETE_USER',
    EDIT_USER: 'USERS/EDIT_USER'
}

export const ORDERS = {
    GET_DEFAULT_ORDERS: 'ORDERS/GET_DEFAULT_ORDERS',
    DELETE_ORDER: 'ORDERS/DELETE_ORDER',
    EDIT_ORDER: 'ORDERS/EDIT_ORDER',
    SET_DEFAULT_ORDER: 'ORDERS/SET_DEFAULT_ORDER',
}
