export const SERVICES = {
    GET_DEFAULT_SERVICES_ICE: 'SERVICES/GET_DEFAULT_SERVICES_ICE',
    SET_DEFAULT_SERVICE: 'SERVICES/SET_DEFAULT_SERVICE',
    DELETE_SERVICE: 'SERVICES/DELETE_SERVICE',

    GET_DEFAULT_SERVICES_SUSPENSION: 'SERVICES/GET_DEFAULT_SERVICES_SUSPENSION',
    SET_DEFAULT_SERVICE_SUSPENSION: 'SERVICES/SET_DEFAULT_SERVICE_SUSPENSION',
    DELETE_SERVICE_SUSPENSION: 'SERVICES/DELETE_SERVICE_SUSPENSION',

    GET_DEFAULT_SERVICES_ELECTRICIAN: 'SERVICES/GET_DEFAULT_SERVICES_ELECTRICIAN',
    SET_DEFAULT_SERVICE_ELECTRICIAN: 'SERVICES/SET_DEFAULT_SERVICE_ELECTRICIAN',
    DELETE_SERVICE_ELECTRICIAN: 'SERVICES/DELETE_SERVICE_ELECTRICIAN',
}

export const EMPLOYEES = {
    GET_DEFAULT_EMPLOYEES: 'EMPLOYEES/GET_DEFAULT_EMPLOYEES',
    SET_DEFAULT_EMPLOYEE: 'EMPLOYEES/SET_DEFAULT_EMPLOYEE',
    DELETE_EMPLOYEE: 'EMPLOYEES/DELETE_EMPLOYEE',
}
