export const SERVICES = {
    GET_DEFAULT_SERVICES_ICE: 'SERVICES/GET_DEFAULT_SERVICES_ICE',
    GET_DEFAULT_SERVICES_SUSPENSION: 'SERVICES/GET_DEFAULT_SERVICES_SUSPENSION',
    GET_DEFAULT_SERVICES_ELECTRICIAN: 'SERVICES/GET_DEFAULT_SERVICES_ELECTRICIAN'
}
